name: Sentiment Analysis CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda.yaml
          environment-name: mlflow-env
          init-shell: bash
          cache-downloads: true

      - name: Run Training Script (manual)
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate mlflow-env
          python model_ci.py --data_path scripts/processed_reviews_clinique.csv
