name: CI Sentiment Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Git LFS Pull
        run: |
          git lfs install
          git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run MLflow project
        run: |
          mlflow run . --env-manager=local

      - name: Save mlruns to repo
        run: |
          git config --global user.name "${{ secrets.SECRETS_USERNAME }}"
          git config --global user.email "${{ secrets.SECRETS_EMAIL }}"
          git add mlruns/
          git commit -m "Save mlruns from CI run"
          git push origin main
