name: Text Preprocessing Pipeline

on:
  push:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Git LFS Pull
      run: |
        git lfs install
        git lfs pull

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        pip install pandas nltk joblib scikit-learn
        python -m nltk.downloader punkt_tab stopwords

    - name: Run preprocessing script
      run: python scripts/main.py

    - name: Upload output artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-data
        path: |
          processed_reviews_clinique.csv
          output/text_preprocessor.joblib
